name: ColaBick
favicon: null
layout_spectrum: 0.8248135594185442
typography_spectrum: 0.624642520211637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.16319862520322204
  lightness: 0.1952687595039606
  saturation: 0.15435373899526894
  rhythmicContrast: 0.3577146122697741
purpose: []
